version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html:cached
        networks:
            - laravel
        depends_on:
            - db
        deploy:
            resources:
                limits:
                    cpus: '4'        # Limite à 2 CPU
                    memory: 6G       # Limite la mémoire à 2 Go
                reservations:
                    memory: 1G       # Réserve 1 Go de mémoire minimale

    node:
        image: node:16-alpine
        container_name: node_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html:cached
        networks:
            - laravel
        command: sh -c "npm install && npm run dev"

    webserver:
        image: nginx:alpine
        container_name: nginx_server
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html:cached
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:
